### ISSUE TITLE
ipv6-on-nameservers finding incorrect

### ISSUE THREAD

**Issue by sigio** [minvws/nl-kat-coordination#115]
Kat is reporting (for all nameservers detected) that they don't have ipv6, while this is clearly not the case.
(example of found nameservers that kat claims don't have ipv6 include: ns[1234].luadns.net, ns0.rijksoverheidnl.com ns1.rijksoverheidnl.nl ns2.rijksoverheidnl.eu etc)

Boefjes has ipv6 internet access

**OpenKAT version**
1.4

**Comment by underdarknl** [comment]
this is probably due to the nameservers not being inside the scope. The new 1.5 model allows some level of cascading to nameservers and should fix this.

**Comment by tobiasBDO** [comment]
> 



> this is probably due to the nameservers not being inside the scope. The new 1.5 model allows some level of cascading to nameservers and should fix this.

I am still experiencing this issue in release `v1.6.0rc3`, does OpenKAT need ipv6 internet access in order to sort this out?

**Comment by underdarknl** [comment]
Is this still happening in 1.7 and up?

**Comment by tobiasBDO** [comment]
> Is this still happening in 1.7 and up?

Have not seen this since!

**Comment by praseodym** [comment]
Closing, feel free to reopen if this occurs with a recent version.
